### PR TITLE
Master

### PR DESCRIPTION
**Pull request by lukechadwick**
Did this backwards accedentally as I created tidying branch first so I'm creating the pull request in reverse

### CODE REVIEW

**Comment by emmanio** [comment]
Hey if you wanna add me as a collaborator I can check out your code and merge your pull request.

**Comment by emmanio** [comment]
just a couple of edits :) 
- Your text needs to be indented from the <p> tags so you can clearly distinguish what's text and what is code.
- Add for your list at 69 - 92 the <a> tag doesn't need to be on a separate line from <li>, you can just add it next to the <li> tag. So what ever is in the <li> tag just needs to go straight after it, it'll be easier to read.

**Comment by emmanio** [comment]
just a couple of edits 
Your text needs to be indented from the <p> tags so you can clearly distinguish what's text and what is code.
Add for your list at 69 - 92 the <a> tag doesn't need to be on a separate line from <li>, you can just add it next to the <li> tag. So what ever is in the <li> tag just needs to go straight after it, it'll be easier to read.

**Comment by emmanio** [comment]
just a couple of edits :) 
Your text needs to be indented from the p tags so you can clearly distinguish what's text and what is code.

Add for your list at 69 - 92 the a tag doesn't need to be on a separate line from li, you can just add it next to the li tag. So what ever is in the li tag just needs to go straight after it, it'll be easier to read.

**Comment by lukechadwick** [comment]
Thanks for the corrections Emma, appreciate it.

**Pull request merged**
